# Generated by Django 2.2.9 on 2020-01-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('phone', models.CharField(max_length=100, verbose_name='전화번호')),
                ('address', models.TextField(verbose_name='주소')),
            ],
        ),
    ]
