# Generated by Django 2.2.9 on 2020-01-25 12:49

from django.db import migrations, models
import django.db.models.deletion
import mysite.utils


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='제품명')),
                ('photo', models.ImageField(upload_to=mysite.utils.uuid_upload_to, verbose_name='제품 사진')),
                ('content', models.TextField(verbose_name='제품 설명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('left', models.PositiveIntegerField(verbose_name='남은 수량')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Account', verbose_name='거래처')),
            ],
        ),
    ]
