# Generated by Django 2.2.9 on 2020-01-25 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stock.Account', verbose_name='거래처'),
        ),
    ]
